services:
  pgtyped-db:
    container_name: "pgtyped-postgresql"
    image: postgres:14.6-alpine
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      PGDATA: /var/lib/postgresql/data
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
