import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { Avatar, Card, Image, Text } from "@mantine/core";

export default function Home() {
  const user = api.example.getUser.useQuery();

  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen items-center justify-center">
        <Card shadow="sm" padding="xl" radius="md" withBorder>
          <Avatar
            mx="auto"
            src={user.data ? user.data.avatar : ""}
            radius={100}
            size="150px"
          ></Avatar>
          <Text ta="center" fz="lg" weight={500} mt="md">
            {user.data ? user.data.name : ""}
          </Text>
          <Text ta="center" c="dimmed" fz="sm">
            {user.data ? user.data.mail : ""}
            {user.data ? "・" : ""}
            {user.data ? user.data.position : ""}
          </Text>
        </Card>
      </div>
    </>
  );
}
